# FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
# FROM mcr.microsoft.com/windows/servercore:ltsc2022
FROM mcr.microsoft.com/windows/servercore:ltsc2019

SHELL ["cmd", "/S", "/C"]

COPY install-tools.ps1 .

# RUN .\install-tools.ps1

# WORKDIR /azp
# COPY install-agent.ps1 .

# CMD powershell .\install-agent.ps1